version: "3"

services:
  mysql:
    image: mysql:8.0.28
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}

  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    volumes:
      - ./api:/stock-rails
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: /bin/bash -c "rails s -b 0.0.0.0"

  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    volumes:
      - ./web:/usr/src/stock-next
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - api
    command: /bin/bash -c "WATCHPACK_POLLING=true yarn dev"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
