POST http://stock.com/api/v1/users HTTP/1.1
# Authorization: Bearer {{ authToken_dev }}
content-type: application/json

{
  "user": {
    "name": "test",
    "email": "test@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }
}
